const express = require('express')
const router = express.Router()

const { getPosts } = require('./getPosts')
const { getSinglePost } = require('./getSinglePost')
const { addCount } = require('./addCount')
const { getFeaturedPosts } = require('./getFeaturedPosts')
const { getLatestPosts } = require('./getLatestPosts')
const { getTags } = require('./getTags')
const { getCategories } = require('./getCategories')
const { getAuthorPosts } = require('./getAuthorPosts')
const { searchPosts } = require('./searchPosts')
const { verifyToken } = require('../auth/verifyToken')
const { deletePost } = require('./deletePost')
const { createPost, editPost, uploadMiddleware } = require('./uploadPost')

router.get('/posts', getPosts)
router.get('/post', getSinglePost, addCount)
router.get('/featured', getFeaturedPosts)
router.get('/latest-posts', getLatestPosts)
router.get('/tags', getTags)
router.get('/categories', getCategories)
router.get('/author', getAuthorPosts)
router.get('/search', searchPosts)
router.delete('/post', verifyToken, deletePost)
router.post('/post', verifyToken, uploadMiddleware.single('file'), createPost)
router.put('/post', verifyToken, uploadMiddleware.single('file'), editPost)

module.exports = router